/**
 * Compliance with Argon Core's component contract.
 *
 * Argon's rules are enforced only at render time in a live world, which made every
 * violation cost a reload cycle to find. These tests check our components against
 * a snapshot extracted from Argon's own source (tests/fixtures/argon-contract.json,
 * regenerated by `npm run sync:argon`), so the same mistakes fail at `npm test`.
 *
 * Between them these checks cover every contract bug hit during the migration.
 */

import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { resolveArgonPath, extractArgonContract } from '../tools/argon-contract.mjs';

const require = createRequire(import.meta.url);
const CONTRACT = require('./fixtures/argon-contract.json');

const argonDir = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'scripts', 'argon');

const sources = fs
  .readdirSync(argonDir)
  .filter((file) => file.endsWith('.mjs'))
  .map((file) => ({ file, source: fs.readFileSync(path.join(argonDir, file), 'utf8') }));

/** Our component classes, with the class body and the base they extend. */
const components = sources.flatMap(({ file, source }) => {
  const matches = [...source.matchAll(/class\s+(\w+)\s+extends\s+([\w.]+)\s*\{/g)];

  return matches.map((match, index) => {
    const start = match.index;
    const end = index + 1 < matches.length ? matches[index + 1].index : source.length;
    return {
      file,
      name: match[1],
      parentExpression: match[2],
      base: match[2].split('.').pop(),
      body: source.slice(start, end)
    };
  });
});

const ourClassNames = new Set(components.map((c) => c.name));

describe('Contract snapshot', () => {
  it('describes the classes we build on', () => {
    expect(Object.keys(CONTRACT.classes).length).toBeGreaterThan(10);
    expect(CONTRACT.partials).toContain('ActionPanel');
  });

  it('found our components', () => {
    expect(components.length).toBeGreaterThan(8);
  });
});

describe('Inheritance depth', () => {
  it('extends an Argon base directly, never one of our own classes', () => {
    // Argon resolves templates from the IMMEDIATE parent class name, so a
    // two-deep subclass requests a partial that does not exist.
    const twoDeep = components.filter((c) => ourClassNames.has(c.base));
    const detail = twoDeep.map((c) => `${c.file}: ${c.name} extends ${c.base}`).join('\n  ');
    expect(twoDeep, `would request a missing template:\n  ${detail}`).toEqual([]);
  });

  it('extends a class Argon actually defines', () => {
    for (const component of components) {
      expect(component.parentExpression, `${component.file}: ${component.name}`).toMatch(/^ARGON\./);
      expect(CONTRACT.classes, `${component.name} extends unknown ${component.base}`).toHaveProperty(component.base);
    }
  });

  it('resolves to a template Argon ships', () => {
    for (const component of components) {
      expect(CONTRACT.partials, `${component.name} -> ${component.base}.hbs`).toContain(component.base);
    }
  });
});

describe('Abstract methods', () => {
  it('implements every abstract method of the base class', () => {
    const missing = [];

    for (const component of components) {
      const required = CONTRACT.classes[component.base]?.abstractMethods ?? [];
      for (const method of required) {
        // A method Argon only warns about at runtime; absence is silent breakage.
        if (!new RegExp(`\\b${method}\\s*\\(`).test(component.body)) {
          missing.push(`${component.file}: ${component.name} must implement ${method}() from ${component.base}`);
        }
      }
    }

    expect(missing, `\n  ${missing.join('\n  ')}`).toEqual([]);
  });
});

describe('Accessor pairs', () => {
  it('never overrides a getter whose base also defines a setter', () => {
    // Redeclaring only the getter shadows the inherited setter, so any assignment
    // throws "Cannot set property X which has only a getter".
    const shadowed = [];

    for (const component of components) {
      const pairs = CONTRACT.classes[component.base]?.accessorPairs ?? [];
      for (const accessor of pairs) {
        const hasGetter = new RegExp(`get\\s+${accessor}\\s*\\(`).test(component.body);
        const hasSetter = new RegExp(`set\\s+${accessor}\\s*\\(`).test(component.body);
        if (hasGetter && !hasSetter) {
          shadowed.push(`${component.file}: ${component.name} overrides get ${accessor}() without set ${accessor}()`);
        }
      }
    }

    expect(shadowed, `\n  ${shadowed.join('\n  ')}`).toEqual([]);
  });
});

describe('Constructor options', () => {
  it('passes options whose default is undefined rather than relying on it', () => {
    // e.g. ItemButton's `inActionPanel = undefined` resolves to `isWeaponSet`
    // (false), silently styling the button for the accordion list instead of the
    // action bar, where it collapses to zero width.
    const risky = [];

    for (const component of components) {
      const options = CONTRACT.classes[component.base]?.constructorOptions ?? [];
      const undefaulted = options.filter((option) => option.default === 'undefined').map((o) => o.name);
      if (!undefaulted.length) continue;

      for (const { source, file } of sources) {
        const constructions = [...source.matchAll(new RegExp(`new\\s+${component.name}\\(\\{([^}]*)\\}`, 'g'))];
        for (const [, args] of constructions) {
          for (const option of undefaulted) {
            if (!args.includes(option)) {
              risky.push(`${file}: new ${component.name}({...}) omits "${option}" (Argon default is undefined)`);
            }
          }
        }
      }
    }

    expect(risky, `\n  ${risky.join('\n  ')}`).toEqual([]);
  });
});

describe('Structural classes', () => {
  it('extends the base class list rather than replacing it', () => {
    // Argon's layout lives on the class its base returns — `portrait-hud` carries
    // min-width/min-height, `actions-container` carries the flex layout. Returning
    // a bare array drops them and the component collapses.
    const replaced = components
      .filter((c) => /get classes\(\)/.test(c.body))
      .filter((c) => {
        const body = c.body.match(/get classes\(\)\s*\{([\s\S]*?)\}/)?.[1] ?? '';
        return !body.includes('super.classes');
      })
      .map((c) => `${c.file}: ${c.name}.classes does not spread super.classes`);

    expect(replaced, `\n  ${replaced.join('\n  ')}`).toEqual([]);
  });
});

describe('Button icons', () => {
  it('uses image paths, not Font Awesome classes', () => {
    // ActionButton and ButtonPanelButton assign `icon` to a CSS background-image.
    for (const { file, source } of sources) {
      const fontAwesome = [...source.matchAll(/['"`](fa[srlbd]?[\s-]fa-[\w-]+)['"`]/g)].map((m) => m[1]);
      expect(fontAwesome, `${file} uses Font Awesome where an image path is required`).toEqual([]);
    }
  });
});

const argonPath = resolveArgonPath();

describe.skipIf(!argonPath)('Installed Argon matches the committed contract', () => {
  it('has not drifted — run `npm run sync:argon` if this fails', () => {
    expect(extractArgonContract(argonPath)).toEqual(CONTRACT);
  });
});
